#!/bin/bash

echo "## Documentation" > DOCUMENTATION.mdt
echo "You can see below the API reference of this module." >> DOCUMENTATION.mdt

write () {
    echo "Generating docs for $1"
    blah -d $1
    echo "# \`$1\`" >> DOCUMENTATION.mdt
    cat DOCUMENTATION.md >> DOCUMENTATION.mdt
}

write lib/index.js
write lib/composition/index.js
write lib/composition/parsers/convert-to-on.js
write lib/composition/parsers/flow-component.js
write lib/composition/parsers/flow-elements.js
write lib/composition/parsers/line-type.js
write lib/composition/parsers/method.js
write lib/composition/node/subelm/index.js
write lib/composition/node/index.js
write lib/composition/line/index.js
mv DOCUMENTATION.mdt DOCUMENTATION.md
